#define _BITWISE_AND 0
#define _BITWISE_OR 1
#define _COMMA 2
#define _FINALLY 3
#define _LPAREN 4
#define _RPAREN 5
#define _IDENTIFIER 6
#define _EQUALS 7
#define _DOT 8
#define _CLASS 9
#define _PUBLIC 10
#define _PRIVATE 11
#define _SEMICOLON 12
#define _COLON 13
#define _OR 14
#define _RETURN 15
#define _TRY 16
#define _SYNCHRONIZED 17
#define _THROW 18
#define _BREAK 19
#define _CONTINUE 20
#define _CATCH 21
#define _FINAL 22
#define _IF 23
#define _ELSE 24
#define _WHILE 25
#define _FOR 26
#define _LSPAR 27
#define _RSPAR 28
#define _TIMES_EQUALS 29
#define _DIVIDE_EQUALS 30
#define _MOD_EQUALS 31
#define _PLUS_EQUALS 32
#define _MINUS_EQUALS 33
#define _LEFT_SHIFT_EQUALS 34
#define _RIGHT_SHIFT_EQUALS 35
#define _UNSIGNED_RIGHT_SHIFT_EQUALS 36
#define _AND_EQUALS 37
#define _XOR_EQUALS 38
#define _OR_EQUALS 39
#define _QUESTION 40
#define _NOT_EQUALS 41
#define _LT 42
#define _GT 43
#define _LE 44
#define _GE 45
#define _INSTANCEOF 46
#define _AND 47
#define _XOR 48
#define _PLUS 49
#define _MINUS 50
#define _TIMES 51
#define _DIVIDE 52
#define _MOD 53
#define _PLUS_PLUS 54
#define _MINUS_MINUS 55
#define _TILDE 56
#define _THIS 57
#define _SUPER 58
#define _INT 59
#define _LONG 60
#define _SHORT 61
#define _BYTE 62
#define _CHAR 63
#define _IMPLEMENTS 64
#define _FLOAT 65
#define _DOUBLE 66
#define _BOOLEAN 67
#define _VOID 68
#define _NOT 69
#define _EXTENDS 70
#define _RMPARA 71
#define _LMPARA 72
#define _STATIC 73
#define _LEFT_SHIFT 74
#define _RIGHT_SHIFT 75
#define _UNSIGNED_RIGHT_SHIFT 76
#define _LITERAL 77
#define _THROWS 78
#define _NEW_KEYWORD 79
#define _IMPORT 80
#define _ASTERISK 81
#define _PACKAGE 82
#define _INTERFACE 83
#define _EQUALS_EQUALS 84
