/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_acclist[419] =
    {   0,
        4,    4,   20,   18,   19,    1,   18,   19,    2,   19,
       16,   18,   19,   18,   19,   17,   18,   19,   16,   18,
       19,   16,   18,   19,   18,   19,   15,   18,   19,   16,
       18,   19,   16,   18,   19,   16,   18,   19,   15,   18,
       19,   16,   18,   19,   10,   18,   19,   10,   18,   19,
       16,   18,   19,   16,   18,   19,   16,   18,   19,   16,
       18,   19,   16,   18,   19,   16,   18,   19,   17,   18,
       19,   17,   18,   19,   17,   18,   19,   17,   18,   19,
       17,   18,   19,   17,   18,   19,   17,   18,   19,   17,
       18,   19,   17,   18,   19,   17,   18,   19,   17,   18,

       19,   17,   18,   19,   17,   18,   19,   17,   18,   19,
       17,   18,   19,   17,   18,   19,   17,   18,   19,   17,
       18,   19,   17,   18,   19,   17,   18,   19,   16,   18,
       19,    4,   19,   19,    5,   19,   16,   12,   17,    8,
       11,    3,    2,   11,   10,   11,   10,   10,   15,   16,
       16,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   14,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   14,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,    4,    5,    6,   12,   12,   11,   11,    2,   11,
       10,   10,   10,   11,   10,   10,   10,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       14,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   11,   11,   11,   10,   10,   11,   11,
       10,   10,   10,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,    7,   17,   14,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,    9,   17,   17,   17,
       17,   11,   11,   11,   17,   17,   17,   17,   17,   17,
       17,   17,   14,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   14,   17,   17,   17,   11,   11,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       13,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   14,   17,   17
    } ;

static yyconst short int yy_accept[407] =
    {   0,
        1,    1,    1,    2,    3,    4,    6,    9,   11,   14,
       16,   19,   22,   25,   27,   30,   33,   36,   39,   42,
       45,   48,   51,   54,   57,   60,   63,   66,   69,   72,
       75,   78,   81,   84,   87,   90,   93,   96,   99,  102,
      105,  108,  111,  114,  117,  120,  123,  126,  129,  132,
      134,  135,  137,  138,  138,  139,  139,  140,  140,  141,
      141,  141,  142,  143,  144,  145,  146,  146,  146,  147,
      147,  148,  148,  148,  149,  149,  150,  151,  152,  153,
      154,  155,  156,  157,  158,  159,  160,  161,  162,  164,
      165,  166,  167,  168,  169,  170,  171,  172,  174,  175,

      176,  177,  178,  179,  180,  181,  182,  183,  184,  185,
      186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
      196,  197,  198,  199,  200,  201,  202,  203,  204,  204,
      205,  206,  206,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  208,  209,  209,  209,  210,  211,  211,  212,
      213,  213,  214,  214,  215,  215,  216,  217,  217,  218,
      219,  220,  221,  222,  223,  224,  225,  226,  227,  228,
      229,  230,  231,  232,  233,  234,  235,  236,  237,  238,
      239,  240,  241,  243,  244,  245,  246,  247,  248,  249,
      250,  251,  252,  253,  254,  255,  256,  257,  258,  259,

      260,  261,  262,  263,  264,  265,  266,  267,  268,  269,
      270,  271,  272,  273,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  275,  276,  276,  276,  277,  278,  279,
      279,  280,  281,  281,  281,  281,  282,  283,  283,  283,
      284,  284,  285,  286,  287,  288,  289,  290,  291,  292,
      293,  294,  295,  296,  297,  298,  299,  300,  301,  302,
      303,  304,  305,  305,  307,  309,  310,  311,  312,  313,
      314,  315,  316,  317,  318,  319,  320,  321,  322,  323,
      324,  325,  326,  327,  329,  330,  331,  332,  332,  332,
      332,  332,  332,  332,  332,  332,  333,  333,  334,  334,

      334,  334,  334,  335,  336,  337,  338,  339,  340,  341,
      342,  343,  345,  346,  347,  348,  349,  350,  351,  351,
      352,  353,  354,  355,  356,  357,  358,  359,  360,  361,
      362,  363,  364,  365,  367,  368,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  370,  371,  371,  372,  373,
      374,  375,  376,  377,  378,  379,  380,  381,  381,  382,
      383,  384,  385,  386,  387,  388,  389,  390,  391,  392,
      392,  392,  392,  393,  394,  395,  396,  397,  397,  398,
      399,  400,  401,  402,  403,  404,  405,  405,  406,  407,
      408,  408,  409,  410,  411,  412,  412,  413,  414,  414,

      415,  416,  417,  418,  419,  419
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   33,   34,   33,
        7,    7,    7,    7,    7,   35,    7,    7,    7,   36,
        7,    7,    7,    7,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    3,    4,    1,    1,    3,
        1,    1,    5,    1,    1,    1,    6,    1,    7,    7,
        7,    7,    8,    1,    1,    1,    1,    1,    1,    1,
        8,    8,    8,    8,    9,   10,    4,    1,    3,    1,
        1,   10,    8,    7,    8,    8,    8,    7,    4,    4,
        4,    4,    9,    4,   11,    4,   10,    4,   11,   11,
       11,   11,    4,    4,    4,    4,    4,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[428] =
    {   0,
        0,    0,   69,   70, 1045, 1046, 1046, 1046, 1017,   68,
        0, 1016,   66,   66, 1046, 1015,   63,   64,   77,   68,
       91,  140, 1017,   52, 1013,   57, 1046, 1012,   43,   50,
       93,   71,   64,   89,  982,   67,  981,  980,  108,  978,
      107,  987,  130,  122,  973,   45,   80,  981,  107,    0,
     1046,  134, 1046,  114, 1025,  191,    0, 1020, 1046,  183,
     1012,  235, 1046,    0,  195,  267,  304,  148, 1046,  251,
     1046, 1011,  202,  274,  311, 1046, 1000,  156,  966,  965,
      968,  976,  961,  129,  978,  977,  964,  970,  955,  956,
      953,  138,  961,  958,  956,  952,  949,    0,  952,  146,

      953,  961,  945,  941,  949,  950,  955,  956,  941,  175,
      955,  175,  955,  941,  189,  939,  944,  939,  120,  197,
      946,  933,   51,  940,  929,  942,    0,  248,  262, 1046,
     1046,  301,  159,  221,  322,  343,    0,  377,  335,  348,
        0,    0, 1046,  357,  365,    0,  407,  423,    0, 1046,
      370,  287,  382,  437,    0,  431,    0,  455,  470,  961,
      926,  939,  932,  941,  936,  935,  936,  921,  919,  148,
      935,  933,  929,  921,  918,  926,  912,  928,  927,  913,
      181,  907,  907,  904,  890,  899,  933,  895,  890,  856,
      851,  841,  186,  850,  845,  838,  837,  835,  821,  816,

      808,  811,  786,  788,  772,  775,  775,  782,  768,  781,
      783,  772,  774,  770,  308,  411,  429,  279,  494,  812,
        0,  442,  487,    0,  479,  524,  529,  452, 1046,  461,
      534, 1046,  564,  324,  242,  555, 1046,  579,  575,    0,
      594,  762,  761,  772,  766,  763,  752,  744,  753,  741,
      749,  741,  738,  745,  738,  729,  741,  728,  736,  718,
      723,  712,  713,    0,  712,  728,  708,  715,  710,  705,
      699,  688,  693,  680,  691,  675,  682,  684,  669,  678,
      671,  656,  659,    0,  654,  650,  643,  555,  601,  615,
      333,  603,  623,  647,    0,  654,  622,  684,  629,  377,

      524,  636,  689,  645,  625,  641,  617,  610,  614,  599,
      607,  594,  592,  578,  583,  589,  588,  587,  586,  582,
      569,  559,  564,  557,  551,  543,  529,  524,  532,  529,
      512,  520,  510,  508,  514,  513,  679,  412,  695,  721,
      742,    0,  763,    0,  732, 1046,  747,  518,  481,  472,
      471,  471,  470,  458,  476,  477,  476,  475,  464,  444,
      449,  434,  439,  435,  421,  396,  215,  394, 1046,  795,
      710,    0,  377,  389,  376,  359,  350,  341,  328,  314,
      299,  291,  292,  281,  284,  272,    0,  256,  252,  251,
      245,  245,  228,  203,  175,    0,  159,  152,  139,   91,

      101, 1046,   94,   43, 1046,  834,  845,  853,  864,  875,
      886,  895,  906,  912,  914,  916,  919,  929,  934,  936,
      944,  949,  951,  953,  955,  957,  959
    } ;

static yyconst short int yy_def[428] =
    {   0,
      405,    1,  406,  406,  405,  405,  405,  405,  405,  407,
      408,  405,  405,  409,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  405,  410,
      405,  411,  405,  407,  405,  407,  408,  405,  405,  412,
      405,  405,  405,  413,  405,  405,  405,  405,  405,  405,
      405,  414,  405,   22,  405,  405,  405,  405,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  410,  411,  405,  405,
      405,  405,  407,  407,  407,  407,   56,  407,  405,  405,
      415,   62,  405,  405,  405,  413,  405,  405,   66,  405,
      405,  405,  405,  405,  416,  417,   74,  405,   74,  405,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  405,  418,  418,  407,  138,  405,
      419,  405,  405,  147,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  420,  416,  417,  405,  405,  236,  159,
      405,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  405,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  418,  418,  418,
      418,  421,  418,  138,  422,  405,  405,  405,  405,  420,

      420,  405,  405,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  405,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  418,  418,  418,  418,
      418,  423,  138,  424,  405,  405,  405,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  405,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  405,  418,
      418,  425,  408,  408,  408,  408,  408,  405,  408,  408,
      408,  408,  408,  408,  408,  408,  426,  408,  408,  408,
      405,  408,  408,  408,  408,  427,  408,  408,  405,  408,

      408,  405,  408,  408,    0,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405
    } ;

static yyconst short int yy_nxt[1118] =
    {   0,
        6,    7,    8,    6,    9,   10,   11,   12,   13,   14,
       15,   15,   16,   17,   15,   18,   19,   20,   21,   22,
       22,   22,   22,   23,   15,   24,   25,   26,   27,   15,
       11,   11,   11,   11,   11,   11,   11,   15,    6,   15,
       28,   11,   29,   30,   31,   32,   33,   34,   35,   11,
       36,   11,   37,   38,   39,   40,   41,   11,   42,   43,
       44,   45,   46,   47,   11,   48,   11,   15,   49,   15,
       27,   51,   51,   55,   53,   59,   53,   77,   53,   53,
       63,   52,   52,   53,   78,   64,   79,  122,   98,   53,
       53,   53,   53,   61,   53,   62,   62,   62,   62,   62,

      123,  210,   80,  211,   60,   81,   56,   65,   82,   66,
       66,   66,   66,   67,   98,   83,   90,   88,   91,  131,
       99,  100,   68,   69,   70,   71,   89,   72,   92,  124,
      125,   93,   73,   53,   68,   84,   69,   70,   69,   94,
      404,   95,   85,   71,   96,   86,  129,   98,   87,  108,
      103,  130,   56,  109,  104,   72,   65,  403,   74,   74,
       74,   74,   74,  105,  131,  110,  152,  152,  111,  106,
      205,  119,   69,   70,   71,   53,  113,   98,  206,  114,
      120,   75,   53,  160,  402,   69,   70,   69,  166,  167,
      115,  116,   71,  117,  175,  118,  133,   56,  176,   98,

      134,  139,  139,  139,  140,  182,  183,  248,  249,  135,
      135,  135,  136,  147,  147,  147,  147,  147,   98,  195,
       67,   67,   67,   67,   67,  192,  131,   69,  148,  137,
      193,  200,  196,  257,  134,  197,  258,  401,  134,  207,
       69,  148,   69,   73,  141,  134,  269,  201,  270,  134,
      134,  134,  138,  142,  142,  142,  142,  142,  208,   56,
      405,  384,   98,   98,  153,  405,  153,  143,  144,  154,
      154,  154,  154,  154,  129,  385,  145,  238,  400,  130,
      143,  144,  143,   65,  131,  149,  149,  149,  149,   67,
       98,  399,  157,  157,  157,  157,  157,   98,  238,   69,

       70,  150,  215,  216,  217,  228,  228,  398,  151,  215,
      216,  217,   69,   70,   69,  158,  397,   56,   98,  150,
       65,  229,   67,   67,   67,   67,   67,  131,  230,  159,
      159,  159,  159,  159,  395,  394,   69,   70,  338,  229,
      136,  136,  136,  136,   59,   73,  393,   98,  131,   69,
       70,   69,   75,  140,  140,  140,  140,   59,   98,  238,
       56,  218,  218,  218,  218,  301,  220,  220,  220,  220,
      222,  405,  222,   98,  392,  223,  223,  223,  223,  223,
      238,   56,  131,  142,  142,  142,  142,  142,  149,  149,
      149,  149,   67,  391,  390,  219,  219,  219,  219,  219,

      154,  154,  154,  154,  154,  389,  145,  219,  219,  219,
      219,  151,  238,  289,  290,   56,  291,  369,  301,  219,
      219,  219,  219,  219,  219,  224,  224,  224,  224,  224,
      388,  293,  290,  238,  291,   98,  226,   98,  226,   69,
      148,  227,  227,  227,  227,  227,  386,  235,  225,  292,
      405,  383,   69,  148,   69,  231,  231,  231,  231,  231,
      223,  223,  223,  223,  223,  237,  238,  292,  382,  232,
      228,  228,  239,  157,  157,  157,  157,  157,  233,  228,
      228,  381,  232,  237,  232,  380,  229,  238,  240,  240,
      240,  240,  240,  230,  379,   98,  158,  224,  224,  224,

      224,  224,  230,   98,  229,  296,  296,  296,  296,  296,
       98,  241,  294,  294,  294,  294,  294,  378,  377,  143,
      225,  376,  375,   98,  294,  294,  294,  294,  297,   98,
       98,   98,  143,  374,  143,   98,  294,  294,  294,  294,
      294,  294,  227,  227,  227,  227,  227,  298,  298,  298,
      298,  298,  231,  231,  231,  231,  231,  289,  290,  405,
      291,   69,  373,  368,  367,  301,  232,   98,  366,   98,
      299,  235,  365,   98,   69,  233,   69,   98,   98,  232,
      405,  232,  231,  231,  231,  231,  231,  364,   98,  237,
      238,  405,  302,  292,  302,   98,  239,  303,  303,  303,

      303,  303,  363,  289,  290,  233,  291,  237,  362,  405,
      405,  238,  240,  240,  240,  240,  240,  337,  290,  361,
      291,  340,  340,  340,  341,  289,  290,  405,  291,  360,
      359,  405,  358,   98,   98,  241,  357,  356,   98,  292,
      296,  296,  296,  296,  296,  355,  354,  298,  298,  298,
      298,  298,  353,  292,  303,  303,  303,  303,  303,  352,
       98,  292,  351,  297,  342,  343,  343,  343,  343,  343,
      299,  350,  296,  296,  296,  296,  296,  343,  343,  343,
      343,  289,  290,  349,  291,   98,  143,  348,   98,  343,
      343,  343,  343,  343,  343,  297,   98,  289,  290,  143,

      291,  143,  298,  298,  298,  298,  298,  345,  345,  345,
      345,  345,  289,  290,  336,  291,   69,  292,  335,  334,
      333,  346,  332,  289,  290,  299,  291,   98,  331,   69,
      347,   69,  330,  292,  346,   98,  346,  329,  328,  370,
      370,  370,  370,  327,  289,  290,  326,  291,  292,  325,
      345,  345,  345,  345,  345,  324,  323,  322,  321,  292,
      371,  371,  371,  371,  346,  345,  345,  345,  345,  345,
      320,   98,  319,  347,  318,  317,  316,  346,  315,  346,
      292,  134,  134,  134,  134,  134,  314,  313,  347,   98,
      312,  284,  311,  134,  134,  134,  134,  289,  290,  310,

      291,  309,  308,  307,   98,  134,  134,  134,  134,  134,
      134,   98,   98,  371,  371,  371,  371,   98,  306,  305,
      304,   59,  287,   98,  286,  285,   98,   98,  284,  283,
      282,   98,  281,  292,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   54,  280,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   57,  279,  278,   57,
       57,   57,   57,   57,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,  127,  277,  127,  127,  276,
      127,  127,  127,  127,  127,  127,  128,  275,  128,  128,
      128,  128,  128,  128,  128,  128,  128,   58,  274,  273,

      272,   58,  271,  268,  267,   58,  146,  266,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  156,  156,  156,
      221,  221,  234,  234,  236,  236,  236,  236,  236,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      295,  295,  300,  300,  265,  300,  339,  264,  263,  262,
      339,  261,   98,  260,  339,  344,  344,  372,  372,   58,
       58,  387,  387,  396,  396,  339,  339,  259,   98,  256,
      255,  254,  253,  252,   98,   98,  251,  250,  247,   98,
      246,   98,   98,  245,  244,  243,  242,   53,  214,  213,
      212,   98,  209,  204,  203,  202,  199,  198,  194,  191,

      190,  189,  188,  187,   98,  186,  185,  184,  181,  180,
       98,  179,  178,  177,  174,  173,  172,  171,  170,  169,
      168,  165,  164,  163,  162,  161,   53,  155,   76,   59,
      132,  126,  121,  112,  107,  102,  101,   97,   53,   53,
       76,   53,   53,   53,  405,    5,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,

      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405
    } ;

static yyconst short int yy_chk[1118] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,   10,   13,   14,   17,   24,   24,   18,
       20,    3,    4,   26,   26,   20,   29,   46,  404,   17,
       18,   18,   13,   19,   20,   19,   19,   19,   19,   19,

       46,  123,   29,  123,   14,   30,   10,   21,   30,   21,
       21,   21,   21,   21,   36,   30,   33,   32,   33,   54,
       36,   36,   21,   21,   21,   21,   32,   21,   33,   47,
       47,   34,   21,   49,   21,   31,   21,   21,   21,   34,
      403,   34,   31,   21,   34,   31,   52,  401,   31,   41,
       39,   52,   54,   41,   39,   21,   22,  400,   22,   22,
       22,   22,   22,   39,  133,   41,   68,   68,   41,   39,
      119,   44,   22,   22,   22,   49,   43,   44,  119,   43,
       44,   22,   78,   78,  399,   22,   22,   22,   84,   84,
       43,   43,   22,   43,   92,   43,   56,  133,   92,  398,

       56,   60,   60,   60,   60,  100,  100,  170,  170,   56,
       56,   56,   56,   65,   65,   65,   65,   65,  397,  112,
       73,   73,   73,   73,   73,  110,  134,   65,   65,   56,
      110,  115,  112,  181,   56,  112,  181,  395,   56,  120,
       65,   65,   65,   73,   60,   56,  193,  115,  193,   56,
       56,   56,   56,   62,   62,   62,   62,   62,  120,  134,
      128,  367,  120,  394,   70,  128,   70,   62,   62,   70,
       70,   70,   70,   70,  129,  367,   62,  235,  393,  129,
       62,   62,   62,   66,  218,   66,   66,   66,   66,   66,
      392,  391,   74,   74,   74,   74,   74,  390,  235,   66,

       66,   66,  132,  132,  132,  152,  152,  389,   66,  215,
      215,  215,   66,   66,   66,   74,  388,  218,  386,   66,
       67,  152,   67,   67,   67,   67,   67,  135,  152,   75,
       75,   75,   75,   75,  385,  384,   67,   67,  291,  152,
      135,  135,  135,  135,  139,   67,  383,  382,  136,   67,
       67,   67,   75,  139,  139,  139,  139,  140,  381,  234,
      135,  136,  136,  136,  136,  234,  140,  140,  140,  140,
      144,  291,  144,  380,  379,  144,  144,  144,  144,  144,
      234,  136,  138,  145,  145,  145,  145,  145,  151,  151,
      151,  151,  151,  378,  377,  138,  138,  138,  138,  138,

      153,  153,  153,  153,  153,  376,  145,  138,  138,  138,
      138,  151,  300,  216,  216,  138,  216,  338,  300,  138,
      138,  138,  138,  138,  138,  147,  147,  147,  147,  147,
      375,  217,  217,  300,  217,  374,  148,  373,  148,  147,
      147,  148,  148,  148,  148,  148,  368,  156,  147,  216,
      338,  366,  147,  147,  147,  154,  154,  154,  154,  154,
      222,  222,  222,  222,  222,  156,  156,  217,  365,  154,
      228,  228,  156,  158,  158,  158,  158,  158,  154,  230,
      230,  364,  154,  156,  154,  363,  228,  156,  159,  159,
      159,  159,  159,  228,  362,  361,  158,  225,  225,  225,

      225,  225,  230,  360,  228,  223,  223,  223,  223,  223,
      359,  159,  219,  219,  219,  219,  219,  358,  357,  223,
      225,  356,  355,  354,  219,  219,  219,  219,  223,  353,
      352,  351,  223,  350,  223,  349,  219,  219,  219,  219,
      219,  219,  226,  226,  226,  226,  226,  227,  227,  227,
      227,  227,  231,  231,  231,  231,  231,  288,  288,  301,
      288,  227,  348,  336,  335,  301,  231,  334,  333,  332,
      227,  236,  331,  330,  227,  231,  227,  329,  328,  231,
      301,  231,  233,  233,  233,  233,  233,  327,  326,  236,
      236,  239,  238,  288,  238,  325,  236,  238,  238,  238,

      238,  238,  324,  289,  289,  233,  289,  236,  323,  239,
      239,  236,  241,  241,  241,  241,  241,  290,  290,  322,
      290,  292,  292,  292,  292,  293,  293,  239,  293,  321,
      320,  239,  319,  318,  317,  241,  316,  315,  314,  289,
      297,  297,  297,  297,  297,  313,  312,  299,  299,  299,
      299,  299,  311,  290,  302,  302,  302,  302,  302,  310,
      309,  293,  308,  297,  292,  294,  294,  294,  294,  294,
      299,  307,  296,  296,  296,  296,  296,  294,  294,  294,
      294,  337,  337,  306,  337,  305,  296,  304,  287,  294,
      294,  294,  294,  294,  294,  296,  286,  339,  339,  296,

      339,  296,  298,  298,  298,  298,  298,  303,  303,  303,
      303,  303,  371,  371,  285,  371,  298,  337,  283,  282,
      281,  303,  280,  340,  340,  298,  340,  279,  278,  298,
      303,  298,  277,  339,  303,  276,  303,  275,  274,  340,
      340,  340,  340,  273,  341,  341,  272,  341,  371,  271,
      345,  345,  345,  345,  345,  270,  269,  268,  267,  340,
      341,  341,  341,  341,  345,  347,  347,  347,  347,  347,
      266,  265,  263,  345,  262,  261,  260,  345,  259,  345,
      341,  343,  343,  343,  343,  343,  258,  257,  347,  256,
      255,  254,  253,  343,  343,  343,  343,  370,  370,  252,

      370,  251,  250,  249,  248,  343,  343,  343,  343,  343,
      343,  247,  246,  370,  370,  370,  370,  245,  244,  243,
      242,  220,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  370,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  407,  203,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  408,  202,  201,  408,
      408,  408,  408,  408,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  410,  200,  410,  410,  199,
      410,  410,  410,  410,  410,  410,  411,  198,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  412,  197,  196,

      195,  412,  194,  192,  191,  412,  413,  190,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  414,  414,  414,
      415,  415,  416,  416,  417,  417,  417,  417,  417,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      419,  419,  420,  420,  189,  420,  421,  188,  187,  186,
      421,  185,  184,  183,  421,  422,  422,  423,  423,  424,
      424,  425,  425,  426,  426,  427,  427,  182,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  126,  125,
      124,  122,  121,  118,  117,  116,  114,  113,  111,  109,

      108,  107,  106,  105,  104,  103,  102,  101,   99,   97,
       96,   95,   94,   93,   91,   90,   89,   88,   87,   86,
       85,   83,   82,   81,   80,   79,   77,   72,   61,   58,
       55,   48,   45,   42,   40,   38,   37,   35,   28,   25,
       23,   16,   12,    9,    5,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,

      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#define INITIAL 0
#line 2 "main.l"
    /* Declaration */
    #include <bits/stdc++.h>
    using namespace std;
    #include "Tokens.h"
    #include "data.h"
    #include "data.cpp"
    #include "main.tab.h"
    map<string, int >mp = { {"continue", _CONTINUE}, {"for", _FOR}, {"new", _NEW_KEYWORD}, {"if", _IF}, {"package", _PACKAGE}, {"synchronized", _SYNCHRONIZED}, {"boolean", _BOOLEAN}, {"private", _PRIVATE}, {"this", _THIS}, {"break", _BREAK}, {"double", _DOUBLE}, {"implements", _IMPLEMENTS}, {"throw", _THROW}, {"byte", _BYTE}, {"else", _ELSE}, {"import", _IMPORT}, {"public", _PUBLIC}, {"throws", _THROWS}, {"instanceof", _INSTANCEOF}, {"return", _RETURN}, {"catch", _CATCH}, {"extends", _EXTENDS}, {"int", _INT}, {"short", _SHORT}, {"try", _TRY}, {"char", _CHAR}, {"final", _FINAL}, {"interface", _INTERFACE}, {"static", _STATIC}, {"void", _VOID}, {"class", _CLASS}, {"finally", _FINALLY}, {"long", _LONG}, {"float", _FLOAT}, {"super", _SUPER}, {"while", _WHILE}, {"(", _LPAREN}, {")", _RPAREN}, {"{", _LMPARA}, {"}", _RMPARA}, {"[", _LSPAR}, {"]", _RSPAR}, {";", _SEMICOLON}, {",", _COMMA}, {".", _DOT}, {"=", _EQUALS}, {">", _GT}, {"<", _LT}, {"!", _NOT}, {"~", _TILDE}, {"?", _QUESTION}, {":", _COLON}, {"==", _EQUALS}, {"<=", _LE}, {">=", _GE}, {"!=", _NOT_EQUALS}, {"&&", _AND}, {"||", _OR}, {"++", _PLUS_PLUS}, {"--", _MINUS_MINUS}, {"+", _PLUS}, {"-", _MINUS}, {"*", _TIMES}, {"/", _DIVIDE}, {"^", _XOR}, {"%", _MOD}, {"<<", _LEFT_SHIFT}, {">>", _RIGHT_SHIFT}, {">>>", _UNSIGNED_RIGHT_SHIFT}, {"+=", _PLUS_EQUALS}, {"-=", _MINUS_EQUALS}, {"*=", _TIMES_EQUALS}, {"/=", _DIVIDE_EQUALS}, {"&=", _AND_EQUALS}, {"|=", _OR_EQUALS}, {"^=", _XOR_EQUALS}, {"%=", _MOD_EQUALS}, {"<<=", _LEFT_SHIFT_EQUALS}, {">>=", _RIGHT_SHIFT_EQUALS}, {">>>=", _UNSIGNED_RIGHT_SHIFT_EQUALS}}; 
#define comment 1

#line 821 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 107 "main.l"

    /* Rules */
#line 986 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 406 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1046 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 109 "main.l"
{;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "main.l"
{;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 111 "main.l"
BEGIN(comment);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "main.l"
{;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "main.l"
{;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 114 "main.l"
BEGIN(INITIAL);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;
                                
                                string type_str = "null";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 126 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;

                                string type_str = "char";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;

                                string type_str = "boolean";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 146 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;

                                string type_str = "int";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 156 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;

                                string type_str = "float";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 166 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;

                                string type_str = "string";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 176 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;

                                string type_str = "textblock";
                                char * type = new char[type_str.length() + 1];
                                strcpy(type, type_str.c_str());
                                yylval.elem->type = type;
                                return LITERAL;
                            }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 186 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;
                                switch(mp[strdup(yytext)])
                                {
                                    case _CONTINUE:return CONTINUE;
                                    case _FOR:return FOR;
                                    case _NEW_KEYWORD:return NEW;
                                    case _IF:return IF;
                                    case _PACKAGE:return PACKAGE;
                                    case _SYNCHRONIZED:return SYNCHRONIZED;
                                    case _BOOLEAN:return BOOLEAN;
                                    case _PRIVATE:return PRIVATE;
                                    case _THIS:return THIS;
                                    case _BREAK:return BREAK;
                                    case _DOUBLE:return DOUBLE;
                                    case _IMPLEMENTS:return IMPLEMENTS;
                                    case _THROW:return THROW;
                                    case _BYTE:return BYTE;
                                    case _ELSE:return ELSE;
                                    case _IMPORT:return IMPORT;
                                    case _PUBLIC:return PUBLIC;
                                    case _THROWS:return THROWS;
                                    case _INSTANCEOF:return INSTANCEOF;
                                    case _RETURN:return RETURN;
                                    case _CATCH:return CATCH;
                                    case _EXTENDS:return EXTENDS;
                                    case _INT:return INT;
                                    case _SHORT:return SHORT;
                                    case _TRY:return TRY;
                                    case _CHAR:return CHAR;
                                    case _FINAL:return FINAL;
                                    case _INTERFACE:return INTERFACE;
                                    case _STATIC:return STATIC;
                                    case _VOID:return VOID;
                                    case _CLASS:return CLASS;
                                    case _FINALLY:return FINALLY;
                                    case _LONG:return LONG;
                                    case _FLOAT:return FLOAT;
                                    case _SUPER:return SUPER;
                                    case _WHILE:return WHILE;
                                }
                            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 229 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;
                                switch(mp[strdup(yytext)])
                                {
                                    case _LPAREN:return LPAREN;
                                    case _RPAREN:return RPAREN;
                                    case _LMPARA:return LMPARA;
                                    case _RMPARA:return RMPARA;
                                    case _LSPAR:return LSPAR;
                                    case _RSPAR:return RSPAR;
                                    case _SEMICOLON:return SEMICOLON;
                                    case _COMMA:return COMMA;
                                    case _DOT:return DOT;
                                }
                            }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 245 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;
                                switch(mp[strdup(yytext)])
                                {
                                    case _BITWISE_AND:return BITWISE_AND;
                                    case _BITWISE_OR:return BITWISE_OR;
                                    case _GT:return GT;
                                    case _LT:return LT;
                                    case _NOT:return NOT;
                                    case _TILDE:return TILDE;
                                    case _QUESTION:return QUESTION;
                                    case _COLON:return COLON;
                                    case _EQUALS:return EQUALS;
                                    case _LE:return LE;
                                    case _GE:return GE;
                                    case _NOT_EQUALS:return NOT_EQUALS;
                                    case _AND:return AND;
                                    case _OR:return OR;
                                    case _PLUS_PLUS:return PLUS_PLUS;
                                    case _MINUS_MINUS:return MINUS_MINUS;
                                    case _PLUS:return PLUS;
                                    case _MINUS:return MINUS;
                                    case _TIMES:return TIMES;
                                    case _DIVIDE:return DIVIDE;
                                    case _XOR:return XOR;
                                    case _MOD:return MOD;
                                    case _LEFT_SHIFT:return LEFT_SHIFT;
                                    case _RIGHT_SHIFT:return RIGHT_SHIFT;
                                    case _UNSIGNED_RIGHT_SHIFT:return UNSIGNED_RIGHT_SHIFT;
                                    case _PLUS_EQUALS:return PLUS_EQUALS;
                                    case _MINUS_EQUALS:return MINUS_EQUALS;
                                    case _TIMES_EQUALS:return TIMES_EQUALS;
                                    case _DIVIDE_EQUALS:return DIVIDE_EQUALS;
                                    case _AND_EQUALS:return AND_EQUALS;
                                    case _OR_EQUALS:return OR_EQUALS;
                                    case _XOR_EQUALS:return XOR_EQUALS;
                                    case _MOD_EQUALS:return MOD_EQUALS;
                                    case _LEFT_SHIFT_EQUALS:return LEFT_SHIFT_EQUALS;
                                    case _RIGHT_SHIFT_EQUALS:return RIGHT_SHIFT_EQUALS;
                                    case _UNSIGNED_RIGHT_SHIFT_EQUALS:return UNSIGNED_RIGHT_SHIFT_EQUALS;
                                }
                            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 288 "main.l"
{   
                                yylval.elem = create_node(1, strdup(yytext));
                                yylval.elem->lineno=yylineno;
                                return IDENTIFIER;
                            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 293 "main.l"
{
                                cout << "Couldn't parse: " << strdup(yytext) << endl;
                            }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 296 "main.l"
ECHO;
	YY_BREAK
#line 1340 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(comment):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 406 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 406 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 405);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 296 "main.l"


int yywrap()
{
    return 1;
}
